[package]
name = "august"
description = "A crate & program for converting HTML to plain text."
version = "0.1.0"
license = "LGPL-3.0-or-later"
homepage = "https://gitlab.com/alantrick/august-rust/"
authors = ["Alan Trick <me@alantrick.ca>"]
repository = "https://gitlab.com/alantrick/august-rust/"
keywords = ["text", "html", "converter"]
categories = ["text-processing"]
edition = '2018'


[dependencies]
html5ever = "*"
num-rational = "*"
num-traits = "*"
itertools = "*"
lazy_static = "*"
hyphenation = "*"
textwrap = { version = "*" }
regex = "*"
unicode-segmentation = "*"