[package]
name = "august"
version = "0.1.0"
authors = ["Alan Trick <me@alantrick.ca>"]
edition = "2018"

[dependencies]
html5ever = "*"
num-rational = "*"
num-traits = "*"
itertools = "*"
lazy_static = "*"
hyphenation = "0.7.1"
textwrap = { version = "0.11" }
regex = "1"
unicode-segmentation = "1.1.0"